### ISSUE TITLE
跟你

### ISSUE THREAD

**Issue by william-xue** [132yse/fre#1]

**Comment by xiabeizi** [comment]
伊撒尔大佬加油鸭！！

**Comment by 132yse** [comment]
#9 重构计划，会加油的呜呜呜
issue 不关了，虽然只有两个人，也是动力！

**Comment by watsonhaw** [comment]
喜欢这个框架呀，学习一波

**Comment by zhmushan** [comment]
歌是真的好听~
也许我可以参与到这个项目里来(不过要四月考完试先

**Comment by 132yse** [comment]
> 歌是真的好听~
> 也许我可以参与到这个项目里来(不过要四月考完试先

啥歌(⊙o⊙)…
快来一起搞~

**Comment by zhmushan** [comment]
> > 歌是真的好听~
> > 也许我可以参与到这个项目里来(不过要四月考完试先
> 
> 啥歌(⊙o⊙)…
> 快来一起搞~

你简历里放的哈哈哈

考完就来搞(当然在这之前我要读一下 react, 之前没接触过, 我还想听听 fre 与 polymer 的区别

**Comment by 132yse** [comment]
> > > 歌是真的好听~
> > > 也许我可以参与到这个项目里来(不过要四月考完试先
> > 
> > 
> > 啥歌(⊙o⊙)…
> > 快来一起搞~
> 
> 你简历里放的哈哈哈
> 
> 考完就来搞(当然在这之前我要读一下 react, 之前没接触过, 我还想听听 fre 与 polymer 的区别

哈哈哈
fre 和 polymer 不一样的哈
fre 是 react 的最小实现，它……就是个严重阉割版的 react，但是还是包含了 react 该有的东东，比如 vdom、fiber，还是 react 遵循的原则：不可变、纯函数
polymer 则不然，它是 web-components 框架，应该是没有 vdom 机制的，而且它遵循的是双向绑定，可变，mvvm 原则
其实，polymer 和 vue 1.x 有点类似，不过 polymer 更专注于 web-component

当总的 omi 框架把 vdom 和 web-components 结合起来了：https://github.com/Tencent/omi

**Comment by monkingxue** [comment]
整体架构和 didact 几乎一致，fiber 核心代码几乎一点没变，最好还是写个 ref or thx 吧。

另外 didact 本身的 diff 过于简单，实用性不高，比如说连 key 都不支持，如果要增强实用性这块需要大改。

**Comment by 132yse** [comment]
> 整体架构和 didact 几乎一致，fiber 核心代码……
目前 fre 的 fiber 实现是不正确的
重点不是 diff 没有 keyed
目前 fre 的致命错误在于，没有高低优先级的调度
didiact 也是如此，fre 目前通过宏任务强制每次更新都会高优先级的开启一次遍历……而整个遍历、渲染都是低优先级……这是错误的
至于 diff，我个人认为，由于没有了递归，我觉得 keyed 的重复利用率不会太高
但是确实也是一个缺陷

综上，我大概放假搞下一个版本：
1. 重构 fiber，写死优先级
2. 重构 diff，加 keyed
3. 重构更新策略，争取低优先级任务全为微任务

**Comment by monkingxue** [comment]
> > 整体架构和 didact 几乎一致，fiber 核心代码……
> 
> 目前 fre 的 fiber 实现是不正确的
> 重点不是 diff 没有 keyed
> 目前 fre 的致命错误在于，没有高低优先级的调度
> didiact 也是如此，fre 目前通过宏任务强制每次更新都会高优先级的开启一次遍历……而整个遍历、渲染都是低优先级……这是错误的
> 至于 diff，我个人认为，由于没有了递归，我觉得 keyed 的重复利用率不会太高
> 但是确实也是一个缺陷
> 
> 综上，我大概放假搞下一个版本：
> 
> 1. 重构 fiber，写死优先级
> 2. 重构 diff，加 keyed
> 3. 重构更新策略，争取低优先级任务全为微任务

key 和递归没什么关系，因为 key 解决的 list 比较的问题，而在比较 list 的时候是不用递归的（循环算 mini patches）就好。目前的问题是连续数组和链表在算最小变动的时候难度不一样，所以 react 的 fiber 专门加了 index prop 来支持对链表的类数组访问

**Comment by 132yse** [comment]
> key 和递归没什么关系，因为 key 解决的 list 比较的问题，而在比较 list 的时候是不用递归的（循环算 mini patches）就好。目前的问题是连续数组和链表在算最小变动的时候难度不一样，所以 react 的 fiber 专门加了 index prop 来支持对链表的类数组访问

有关系的，因为递归是同层的遍历，所以对元素的位置比较敏感，很可能 孩子 发生了位置变化，某一个孩子还包含孩子（孙子），那么 keyed 就可以缓存这一对孩孙，而现在 fiber 的遍历行为，已经不存在孙子了，所以 keyed 只是用来缓存孩子

不过 keyed 还是有必要的

我重开了一个 issue 用来讨论重构：https://github.com/132yse/fre/issues/12

**Comment by monkingxue** [comment]
> 递归是同层的遍历...

为什么递归是同层的遍历？同层使用普通的迭代就可以 diff，而不同层的遍历才应该是递归（比如说递归的 DFS 实现）。
而且原先的 stack reconciler 也是不存在所谓「孙子节点」，因为只会保存 children 的信息，而你说带 key 的 children 的 children 改变了，那会复用上层的 dom，只修改最底层的 dom

**Comment by 132yse** [comment]
> > 递归是同层的遍历...
> 
> 为什么递归是同层的遍历？同层使用普通的迭代就可以 diff，而不同层的遍历才应该是递归（比如说递归的 DFS 实现）。
> 而且原先的 stack reconciler 也是不存在所谓「孙子节点」，因为只会保存 children 的信息，而你说带 key 的 children 的 children 改变了，那会复用上层的 dom，只修改最底层的 dom

我说的是，children 的 children 不变，那它应当一起被缓存
递归是存在多层级的，所以同层遍历，对位置更加敏感

我开了新的 issue，可以去看一下

keyed 准备加一下，但是其他的优化措施就不加了
