### ISSUE TITLE
C站 排行榜 忽隐忽现

### ISSUE THREAD

**Issue by ToWeLong** [132yse/fre#101]
C站排行榜有时为空白，请修复

**Comment by 132yse** [comment]
修复了，这里说明一下原因：
在 fre 内部，每次都只能调度一个任务，所以当两个请求同时完成后，只能处理第一个请求结果
所以现在增加了异步队列，每次处理对头，直到队列为空

突然发现好弱智的bug呀hhh

**Comment by ToWeLong** [comment]
@132yse 哈哈哈，修复了就OK的
