### ISSUE TITLE
asnyc component can not be render

### ISSUE THREAD

**Issue by hkc452** [132yse/fre#104]
as mention above，at some specific condition，async component will not render if runtime is out of dime and there is no more ui quene  to invoke

**Comment by 132yse** [comment]
It not called async component, but called `suspense`, which throw a promise.
And now I fixed this, I did something:

First of all, suspense will suspend the reconcileWork through assert WIP is null.

And then, the promise will resolve results, and WIP is the last, and continue next reconcileWork whether or not out of time.

Thanks for your issue~
.
