### ISSUE TITLE
Replacements for lifecycle hooks?

### ISSUE THREAD

**Issue by IniZio** [132yse/fre#11]
Current userEffect runs on rerender

https://github.com/132yse/fre/blob/afee9964b6690c90305e57f278fc02e84f66997f/src/reconciler.js#L54

Any plans to have 'dependency' argument like react e.g.

```js
useEffect(effectFunc, ['dsd'])
```
?

**Comment by 132yse** [comment]
Yes , there is already a plan to add this.
In react , it depends useMemo API
I will make useMemo cume true first 
soon…

**Comment by 132yse** [comment]
this feature is come ture~
