### ISSUE TITLE
useContext问题

### ISSUE THREAD

**Issue by futurepaycc** [132yse/fre#29]
代码:
`
        let { h, render, useState, createContext, useContext } = window.fre
        const ctx = createContext(0)
        function App() {
            const [count, setCount] = useContext(ctx)
            return (
                <div>
                    <h1>{count}</h1>
                    <button onClick={() => setCount(count + 1)}>+</button>
                    <Other />
                </div>
            )
        }
        function Other() {
            const [count, setCount] = useContext(ctx)
            return <h1>{count}</h1>
        }
        render(<App />, document.getElementById('app'))
`

环境：
fre@1.4.6/fre.umd.js
@babel/standalone@7.4.5
chrome 75
现象：
1. 点击 + 按钮， other组件不刷新
2. count 到13 , chrome卡死

@132yse

**Comment by 132yse** [comment]
恭喜你发现了大 bug
我发现我的实现是错误的，等周六日再写一个版本吧

**Comment by 132yse** [comment]
修改了一下，现在的源码能跑通了
但是还是有一点点性能问题，context实现我还需要继续研究
周六日争取搞定~

**Comment by 132yse** [comment]
halo,
我已经修复了这个问题，你可以重新拉一下代码，或者 `npm i fre@1.4.7`升级到最新版本

次数的 useContext 运行良好并且没有性能损失，但我还是不太满意它的实现，抽时间重构下
