### ISSUE TITLE
如何模拟生命周期函数

### ISSUE THREAD

**Issue by futurepaycc** [132yse/fre#31]
> useEffect(() => {
  return () => {
    console.log('will unmount');
  }
}, []);

react的这种形式，无法工作哦

**Comment by 132yse** [comment]
您好，我需要先问一下：
```js
useEffect(() => {
return () => {
console.log('will unmount')
}
}, [])
```
这个返回一个匿名函数，是指的 unmount 吗

```js
useEffect(() => {
console.log('will mount')
}, [])
```

fre 中直接传空数组，不返回匿名函数，指的是 willmount

如果是否返回空函数代表的是不同的，那我需要做一下处理
你能解释一下吗，谢谢啦

**Comment by mindplay-dk** [comment]
The `useEffect()` function in the React API allows the effect to optionally return a cleanup function.

See documentation and example here:

https://reactjs.org/docs/hooks-effect.html#example-using-hooks-1
