### ISSUE TITLE
Again refactor for fre

### ISSUE THREAD

**Issue by 132yse** [132yse/fre#33]
1. add scheduler
2. refactor keyed diff for component
3. use typescript
4. add `useRef` `useCallback`
5. add test

**Comment by 77xi** [comment]
achieve 吧

**Comment by 132yse** [comment]
@77xi 需要时间车垫，有新思路了

**Comment by 77xi** [comment]
不用改了，你水平太差。by：司徒正美

**Comment by 132yse** [comment]
日哦，揉你

**Comment by 132yse** [comment]
新的算法重构完成啦，再沉淀沉淀

**Comment by 132yse** [comment]
搞定调度，接下来研究 context

**Comment by 132yse** [comment]
不行，中文太辣眼睛了，现在和解算法和任务调度都搞完了，还有context没搞，这个可以关掉了
