### ISSUE TITLE
parcel构建问题

### ISSUE THREAD

**Issue by futurepaycc** [132yse/fre#37]
> import { h, render, useState } from 'fre'
>console.log(render)
undefined

fre: 1.4.9

引入其它包测试工程没问题
是不是fre输出包格式有问题？

**Comment by 132yse** [comment]
emmm 怎么啥错都有呀
我正在写 fre 2.0 要不等开学一起发版吧

**Comment by 132yse** [comment]
我这边测试没问题，估计是版本的锅
更新到最新版本就好了
