### ISSUE TITLE
Add callback argument to render()

### ISSUE THREAD

**Issue by mindplay-dk** [132yse/fre#45]
I just noticed in [React docs](https://reactjs.org/docs/react-dom.html#render) that there's a third argument `callback` in ReactDOM's `render()` function:

```
ReactDOM.render(element, container[, callback])
```

According to the docs:

> If the optional callback is provided, it will be executed after the component is rendered or updated.

This would be very useful for testing, at least.

What do you think about adding support for this?

**Comment by 132yse** [comment]
Maybe we can do the same with `options`? For example, I rewrote commit [here](https://github.com/132yse/fre/blob/master/src/reconciler.js#L40)

**Comment by 132yse** [comment]
Hey, let's continue to talk about this. For our test, I think we can add callbacks, but I'm sorry it may take a few days because our school Internet is not work yet.

**Comment by 132yse** [comment]
I added `options.resolve` callback, which seems to solve the current problem.
[here](https://github.com/132yse/fre/blob/master/src/reconciler.js#L150)
It uses like this :
```js
new Promise((resolve, reject) => {
  options.resolve = resolve
  render(<App />, root)
})
```
It is set by `options` and executed after the DOM operations.

**Comment by mindplay-dk** [comment]
Looks like this is done :-)
