### ISSUE TITLE
Property-names get lower-cased?

### ISSUE THREAD

**Issue by mindplay-dk** [132yse/fre#46]
It looks like property-names are getting lower-cased?

For example, `<div className="red">` gets rendered as `<div classname="red">`, which doesn't work, since the property-names are case-sensitive:

![image](https://user-images.githubusercontent.com/103348/65683792-7a01d980-e05e-11e9-935e-17d6cf31f08a.png)

I've been looking through the code, and can't figure out where or how this happens.

If I take the same example and import `h` and `render` from e.g. `preact`, it works fine, so I don't think it's CodeSandbox mangling the code or something? 🤔

I only see one call to `toLowerCase()` in the code, and it applies only to event-handlers.

Any ideas?

**Comment by 132yse** [comment]
Attribute names are automatically lowercase, which is a requirement of HTML
I think we should use `class` instead of `className`, use `onInput` instead of `onChange`
https://github.com/facebook/react/issues/13525
React may also remove className from the react fire, making it more compliant in lowercase and less expensive.

**Comment by mindplay-dk** [comment]
> Attribute names are automatically lowercase, which is a requirement of HTML

Yes, for attributes - `className` isn't an attribute, it's a property.

I brought this up earlier [here](https://github.com/132yse/fre/issues/32#issuecomment-534173102).

JSX attributes generally map to object properties first - and to HTML attributes only as a fallback. This is true in React and most React-likes.

For example, here you can see Preact prefers object properties:

https://github.com/preactjs/preact/blob/master/src/diff/props.js#L97

As does Superfine:

https://github.com/jorgebucaran/superfine/blob/master/src/index.js#L33

The issue here is type-safety. Attributes do not have types - they're always strings, while the values you work with in JS have other types.

For example, `<input type="checkbox" defaultChecked={true}/>` is expected to the set the `defaultChecked` property, which is a boolean, not a string.

This is why JSX attributes map to properties and only *fall back* to attributes.

> We should use `class` instead of `className`

When properties and attributes are supported, you can use either. 🙂

> use `onInput` instead of `onChange`

You don't have to do anything to make that work - in current versions of React, `onChange` works like the DOM `input` event. For example, Preact without the `compat` add-on doesn't do anything specific for either `input` or `change` events - it just maps all event names directly to `addEventListener()` calls, and it just works.

> React may also remove `className` from the React Fire, making it more modern and standard in lowercase and less expensive.

This is similar to what Preact does already:

https://github.com/preactjs/preact/blob/master/src/diff/props.js#L47

It just changes `class` to `className`, the *property*, which may be *marginally* faster than setting the `class` attribute, though this is most likely negligible. They're making this change because `<div class="foo">` is what people are used to seeing in HTML and it's easier to type.

Anyhow, I understand the problem now: properties aren't supported at all right now, and the *browser* normalizes `className` to `classname` when `setAttribute()` gets called.

I'll see about adding some tests for this and submit another PR. 👍

**Comment by 132yse** [comment]
Looking forward to refactoring here, becoming safer and tinyer!
