### ISSUE TITLE
new Context, Suspense and so on...

### ISSUE THREAD

**Issue by 132yse** [132yse/fre#59]
Because the new version adds priority scheduling, it is impossible to reduce the size to 1 kb.
There is some space to support Context, Suspense, and other features.

This issue will be used to discuss them.
Whether it is needed and how to implement?

**Comment by mindplay-dk** [comment]
Context is definitely something I'd like to see.

How about refs? `createRef`, `useRef` and the `ref`-attribute - this is something that's often necessary to make meaningful use of `useEffect`, I think?

**Comment by 132yse** [comment]
@mindplay-dk Oh, I forgot about Ref. It's also necessary.

**Comment by 132yse** [comment]
https://github.com/132yse/fre#useref useRef have done

**Comment by 132yse** [comment]
useContext is ready [here](https://github.com/132yse/fre/blob/master/demo/context.js)
