### ISSUE TITLE
Bug in useMemo (?)

### ISSUE THREAD

**Issue by mindplay-dk** [132yse/fre#63]
I noticed a problem with `useEffect()` - the second argument (changed props) which gets passed on through to `useMemo()`, is not respected: the effect is triggered every time anything updates; even if the component itself doesn't update and another component on the page does.

As you can see in this example, the component should only update if `count` has changed - but the effect runs for all three components:

![image](https://user-images.githubusercontent.com/103348/66552418-91a28d00-eb49-11e9-9ff6-3d267a73bdef.png)

I narrowed it down to to `useMemo()`, where the last time triggers the change every time:

![image](https://user-images.githubusercontent.com/103348/66552691-155c7980-eb4a-11e9-956e-23eda8cf4763.png)

As you can see, it correctly detects that `isChange` is `false` - but still triggers the update, because `isMounted` is always `undefined`.

I will try to add a failing test for this problem.

**Comment by 132yse** [comment]
This seems to be a bug. The code here is not very clear. Maybe I need to refactor it.

**Comment by mindplay-dk** [comment]
Same problem as before, but it's not `useMemo` causing it anymore. 🤔

![image](https://user-images.githubusercontent.com/103348/66562362-cb7c8f00-eb5b-11e9-9637-6623b5780b5e.png)

It could have something to do with the combination of `useState` and `useEffect` maybe?

I've been trying to write a test - it should be simple really:

```jsx
test('useEffect with change detection', async () => {
  let updates = 0

  let effect = () => updates += 1

  const Component = ({ value }) => {
    useEffect(effect, [value])

    return <div>foo</div>
  }

  await testUpdates([
    { content: <Component value={1}/>, test: () => expect(updates).toBe(1) }, // mounted: should trigger effect
    { content: <Component value={2}/>, test: () => expect(updates).toBe(2) }, // updated: should trigger effect
    { content: <Component value={2}/>, test: () => expect(updates).toBe(2) }, // no change: should NOT trigger effect
  ])
})
```

For some reason, the test just runs forever, and `jest` [doesn't time out](https://github.com/facebook/jest/issues/6740#issuecomment-540480091) like it should... I have no idea how to fix this. 😐

**Comment by 132yse** [comment]
I seem to know what you mean. Maybe my understanding of useEffect is biased. 
Can you send me the url of sandbox? I need to debug the use case. Thank you very much.

**Comment by mindplay-dk** [comment]
https://codesandbox.io/s/fre-demo-uxuic

**Comment by mindplay-dk** [comment]
Looks good now, thanks!
