### ISSUE TITLE
Stalling tests: effects not always triggered?

### ISSUE THREAD

**Issue by mindplay-dk** [132yse/fre#66]
As mentioned, I had some problems with tests stalling - it seems the test locks up and runs forever under certain conditions, I'm not sure why.

I worked around it by adding an extra `<div>` wrapper to the `<Component/>` in the tests for `useEffect` that you just merged.

Here's a branch with the extra `<div>` wrappers removed:

https://github.com/132yse/fre/compare/master...mindplay-dk:update-stalling

Can you try this branch on your local system and see if you can find the problem?

I spent a long time on this and I can't figure it out.

Most likely it is caused by a promise that never resolves - so it could have something to do with effects not being triggered; I'm using effects to in `testUpdates` to detect when each update completes... I'm not sure if that's why, but that's my best guess at this point.

**Comment by 132yse** [comment]
Because of jet lag, I'm in bed now.

Tomorrow I will get up and run the branch, I hope I can find the problem 😁

**Comment by 132yse** [comment]
It took me a long time to fix the bug, and now the test is working well 💯
