### ISSUE TITLE
Language version?

### ISSUE THREAD

**Issue by mindplay-dk** [132yse/fre#68]
I noticed you [removed](https://github.com/132yse/fre/commit/fcdd82ede4cd1c1b1369af06bf90b6e2187fc234#diff-bb63f424884a9f20fcf89a0bb63646c9L4) my use of the `...` spread-operator and replaced it with a reference to an old-fashioned `merge()` function.

What version of JS are you targeting?

I personally would prefer writing the library using modern language features and APIs of "evergreen" browsers - since we already have Babel in place, we can compile down to older language versions and let Babel deal with the missing operator.

The ES-module version of the library could leave the source-code as-is, spread operators and all, since ES modules aren't supported in IE anyway.

On that note, the README probably should clarify this point.

**Comment by 132yse** [comment]
I wanted to be compatible with IE at first, because it was possible.

But I used some modern methods, I think we can rewrite the source code in a modern way, and then transfer the compatible code through babel.

So we may need to upgrade the whole code with the modren API.

**Comment by 132yse** [comment]
In fact, I want to rewrite it with Typescript, using standard types and ES6 supersets
In the future, maybe it could be v2, just like preact X, which is a rewrite of all the code.

**Comment by 132yse** [comment]
I removed `merge`, and then will continue use ES6 syntax to ruduce size.

**Comment by mindplay-dk** [comment]
Cool 😎

Yes, TypeScript would be very useful for something like this - I've been using TS since the first stable release, so I'm definitely on board with that. 👍

Although I would suggest you wait until the codebase is fully tested - once you start to add types, you will most likely notice many little things that you'll want to refactor, which will be much safer with good test coverage.

**Comment by 132yse** [comment]
Yes, this will be a future new version with the plan, after we stable the test.

**Comment by 132yse** [comment]
I think we've decided on the language version, and now we can turn it off.
