### ISSUE TITLE
不考虑用ts吗？js不带d.ts的话对ide太不友好了

### ISSUE THREAD

**Issue by rainmanhhh** [132yse/fre#7]
如题

**Comment by 132yse** [comment]
会考虑用 ts 写源码……主要是我 ts 比较菜呜呜呜

**Comment by rainmanhhh** [comment]
> 会考虑用 ts 写源码……主要是我 ts 比较菜呜呜呜

没有启用tslint的情况下直接把.js后缀名改成.ts就行了，可以自动生成d.ts，然后再慢慢改进即可

**Comment by rainmanhhh** [comment]
> > 没有启用tslint的情况下直接把.js后缀名改成.ts就行了，可以自动生成d.ts，然后再慢慢改进即可
> 
> 怎样自动生成 d.ts 呀

tsconfig.json:
compilerOptions下面的declaration设置为true

**Comment by 132yse** [comment]
#9 接下来的重构会换 ts 重写
