### ISSUE TITLE
Problem with useCallback() and useMemo()

### ISSUE THREAD

**Issue by mindplay-dk** [132yse/fre#74]
I think I've spotted a problem with `useMemo` (and `useCallback`) which don't seem to use the `cursor` to create unique states.

```js
export function useCallback (cb, deps) {
  return useMemo(() => cb, deps)
}

export function useMemo (cb, deps) {
  let wip = getWIP()
  if (isChanged(wip._deps, deps)) {
    wip._deps = deps
    return (wip._memo = cb())
  }
  return wip._memo
}
```

These write directly to a `_memo` field, which means you can only call one of these functions, and only once, as it will overwrite this field.

Have a look at [Preact's implementation](https://github.com/preactjs/preact/blob/2f0555878b1b435dbe148d5fe88908a45d2cb624/hooks/src/index.js#L154-L165) for reference.

We should add a test to show that multiple calls to these functions will work correctly. (Actually, anything that relies on side-effects needs to be tested with at least two calls to show that it works.)

**Comment by 132yse** [comment]
Can useMemo be used many times? I don't quite understand its usage sences, but it seems that cursor needs to be added here.

**Comment by mindplay-dk** [comment]
Yes, all hooks can be used many times.

`useMemo` just stores a return-value from a callback, in state - you use it for heavy calculations, to avoid running the function more than once, unless its dependencies have changed.

**Comment by 132yse** [comment]
Okay, if all the hooks can used many times, it seems that I can refactor to reduce size here :grinning:

**Comment by mindplay-dk** [comment]
May be related, but I've noticed an error in `isChanged` sometimes - try this simple test:

```jsx
test('hello', async () => {
  const Component = () => {
    const one = useMemo(() => 1, [])
    useEffect(() => {}); // error in `isChanged` in hooks.js

    return <div/>
  }

  await testRender(<Component/>)
})
```

If you call `useMemo` and then `useEffect`, the call to `useEffect` causes `inChanged` to throw an error.

**Comment by mindplay-dk** [comment]
(I'm not sure how these are related, but if you comment out the `useMemo` line, it works.)

**Comment by 132yse** [comment]
I need a little time to figure out the implement here, Maybe preact should help.

**Comment by 132yse** [comment]
I fixed the bug, and now it's working well.

**Comment by mindplay-dk** [comment]
Seems to work for my use-case 👍 - I will add tests soon.
