### ISSUE TITLE
Something got broken in 1.8.1 or 1.8.0

### ISSUE THREAD

**Issue by mindplay-dk** [132yse/fre#79]
Here's a little experiment I've been working on:

https://codesandbox.io/s/fre-demo-iefch

I wanted to see if it was possible to implement React's class-based `Component` API using hooks.

This was working fine until release `1.8.1` - so the last release that worked for me was `1.8.0`.

Try changing the dependency version from `1.8.0` to `1.8.1` in the sandbox, and all the calls to `setState` for some reason stops working. 😶

I suspected this had something to do with my recent change inlining the setter-function - but I've tried reverting that change, and it still doesn't work, so that's not why.

Here's a [diff between 1.8.0 and 1.8.1](https://diff.intrinsic.com/fre/1.8.0/1.8.1).

Can you spot the problem in these changes?

Whatever it is, it's obviously not covered by tests yet...

**Comment by 132yse** [comment]
How about 1.8.3

**Comment by mindplay-dk** [comment]
> How about 1.8.3

All versions after `1.8.1` affect that example.

Here's another simpler example:

https://codesandbox.io/s/fre-demo-uxuic

This one starts to break with version `1.8.0` already, so the bug may have been partially introduced there.

Watch:

![bug](https://user-images.githubusercontent.com/103348/66906838-9e6f2700-f008-11e9-8d9d-353caa6c9471.gif)

All of a sudden, it's like the scheduler stops accepting new tasks or something?

If you look in the console, you can see event handlers are still firing - it's the calls to the `useState` setters that aren't triggering updates.

Could be related to [this](https://github.com/132yse/fre/commit/4205751169b1c8a124d7adfa01e3906fac98cede#r35521551) maybe?

**Comment by 132yse** [comment]
This looks like 1.8.0 is wrong, in version 1.8.3 I removed `[]` and it worked
```js
const component = useMemo(() => new Component(props));
```

**Comment by mindplay-dk** [comment]
Okay, we still have missing tests for `useEffect` with different `deps` arguments - all the tests use an array right now. If this is the problem, I guess that's why the tests didn't catch it.

That might explain the problem with the first example.

But according to [useMemo docs](https://reactjs.org/docs/hooks-reference.html#usememo):

> If no array is provided, a new value will be computed on every render.

That's not what I want in the first example - I'm passing `[]` because the function has no dependencies and should be executed only on the first render.

And the second example? The error is periodic, as you can see in the GIF - so probably has something to do with the scheduler? Might be two separate problems.

Gotta get the rest of the tests in place...

**Comment by 132yse** [comment]
I'm sorry, your code is correct, I just debugged it, this is indeed my fault, I will fix it as soon as possible, thanks!

**Comment by mindplay-dk** [comment]
Okay, cool - I'll try to get the missing coverage for hooks today, so we can make sure this stuff doesn't break again 🙂

**Comment by 132yse** [comment]
It seems that I really want to fix this bug, and then it should be #80

**Comment by mindplay-dk** [comment]
I'm sorry, I think you misunderstood.

The test was correct - it failed because the effects weren't being triggered correctly.

![image](https://user-images.githubusercontent.com/103348/66933583-94b1e780-f039-11e9-97a1-a545a982cbe2.png)

Now the test is wrong: the same cleanup and effects should not execute more than once!

**Comment by 132yse** [comment]
Can you give me an example with sandbox? the test I am not sure weather it is correct.

**Comment by mindplay-dk** [comment]
> I have to get an example that can be debugged, or I will maintain the status quo.

That's what the tests are for 😉

I guess from the HTML files in the `demo` folder that you're debugging from an HTML page in a browser?

When you run the tests under `node`, you can connect (for example from VS Code or WebStorm, whatever you're using) to the debugger, set breakpoints, inspect variables, run individual tests with a click, and so on - it's definitely worth learning. 🙂

**Comment by mindplay-dk** [comment]
With your last commit, I can confirm that my [sandbox example](https://codesandbox.io/s/fre-demo-fgymz) is now working correctly!

It took me a while to figure out why the test is passing with your change - it looks wrong, but now I see the error in my test! PR on the way! 😁

**Comment by mindplay-dk** [comment]
For the record, the weird problem I [showed above](https://github.com/132yse/fre/issues/79#issuecomment-542616887) where the whole schedule seemed to die - this also no longer seems to occur, so these were probably related. 👍

**Comment by 132yse** [comment]
I published v1.8.5👏
