### ISSUE TITLE
Strange line

### ISSUE THREAD

**Issue by mindplay-dk** [132yse/fre#83]
I'm still concerned about [this line](https://github.com/132yse/fre/blob/5854e5d1e27397789498a8f6036aa1a539c49b1d/src/scheduler.js#L26) in the `scheduler`:

```js
  if (!inMC) planWork() && (inMC = true)
```

`planWork` under `node` is actually `setTimeout`, which returns a *truthy* timer handler, so `inMC = true` *always* executes.

But in the browser, `planWork` is actually `port.postMessage(null)`, which returns `void`, so `inMC = false` *never* executes.

I don't know how come this doesn't seem to matter one way or the other - but it definitely seems like a bug: `planWork` does not have a defined return-value, and that line clearly expects a boolean return-value... You must have meant for this conditional to actually do something?

**Comment by 132yse** [comment]
I tried to get remove it, but the schedule works wrong.
I didn't find the reason. Maybe I'll debug it tomorrow.

**Comment by 132yse** [comment]
I have modified the code, but I can not remove here, because `schedulecallback` can only schedule one task at the same time

**Comment by mindplay-dk** [comment]
Ah, so this is like a global lock to prevent scheduling again if it's already running?

And it wasn't setting this flag in the browser - so that might actually be the reason for the Chrome crash in the benchmark I just mentioned in your Twitter PM.

And we would never see this problem in tests, because it was always setting that lock...

**Comment by 132yse** [comment]
Yes, you are right.

**Comment by 132yse** [comment]
Maybe this issue can also be closed？

**Comment by mindplay-dk** [comment]
Yep, looks good 👍
