### ISSUE TITLE
Add support for functional updates (with setState)

### ISSUE THREAD

**Issue by mindplay-dk** [132yse/fre#93]
Should we add support for [functional updates](https://reactjs.org/docs/hooks-reference.html#functional-updates) with `setState`?

```jsx
function Component() {
  const [state, setState] = useState(0);

  return (
    <button onClick={ setState(count => count + 1) }>
      Count: {count}
    </button>
  )
}
```

For one, this feature simplifies [animations with `requestAnimationFrame`](https://css-tricks.com/using-requestanimationframe-with-react-hooks/#article-header-id-2).

It should be a relatively small change?

**Comment by 132yse** [comment]
Yes, it's a small change that can be supported very quickly🤓

**Comment by 132yse** [comment]
It is now supported :laugh:
